# Compile the one-click Vitrine dashboard launcher (Windows).
# Output: output\Vitrine.exe  plus a Desktop shortcut.
param(
    [switch]$NoShortcut
)

$ErrorActionPreference = 'Stop'
$project = Split-Path $PSScriptRoot -Parent
Set-Location $project

$python = Join-Path $project '.venv\Scripts\python.exe'
if (-not (Test-Path -LiteralPath $python)) {
    throw 'Install the project Python environment first (.venv\Scripts\python.exe).'
}

$csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path -LiteralPath $csc)) {
    throw "C# compiler not found: $csc"
}

$outDir = Join-Path $project 'output'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$ico = Join-Path $PSScriptRoot 'vitrine.ico'
$iconSrc = Join-Path $project 'vitrine\ui\brand\vitrine-icon-dark-256.png'
& $python -c @"
from pathlib import Path
from PIL import Image
src = Path(r'$iconSrc')
dst = Path(r'$ico')
img = Image.open(src).convert('RGBA')
img.save(dst, format='ICO', sizes=[(16, 16), (32, 32), (48, 48), (256, 256)])
print('icon', dst)
"@
if ($LASTEXITCODE -ne 0) { throw 'Failed to write scripts\vitrine.ico' }

$rootCs = Join-Path $PSScriptRoot 'vitrine_launcher_root.cs'
$escaped = $project.Replace('\', '\\').Replace('"', '\"')
@(
    '// Generated by scripts/build_launcher.ps1 — do not edit.'
    'internal static class VitrineRoot'
    '{'
    "    public const string BuiltIn = `"$escaped`";"
    '}'
) | Set-Content -LiteralPath $rootCs -Encoding ASCII

$exe = Join-Path $outDir 'Vitrine.exe'
$src = Join-Path $PSScriptRoot 'vitrine_launcher.cs'
& $csc /nologo /optimize /target:winexe /platform:anycpu `
    /win32icon:$ico `
    /reference:System.Windows.Forms.dll `
    /out:$exe `
    $src $rootCs
if ($LASTEXITCODE -ne 0) { throw 'csc failed' }

$item = Get-Item -LiteralPath $exe
Write-Host ("built {0} ({1:N1} KB)" -f $item.FullName, ($item.Length / 1KB))

if (-not $NoShortcut) {
    $desktop = [Environment]::GetFolderPath('Desktop')
    $lnkPath = Join-Path $desktop 'Vitrine.lnk'
    $ws = New-Object -ComObject WScript.Shell
    $lnk = $ws.CreateShortcut($lnkPath)
    $lnk.TargetPath = $exe
    $lnk.WorkingDirectory = $project
    $lnk.WindowStyle = 1
    $lnk.Description = 'Open the Vitrine preservation dashboard'
    $lnk.IconLocation = "$exe,0"
    $lnk.Save()
    Write-Host "shortcut $lnkPath"
}
